# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edgewood Magicians Guild
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Edgewood Magicians Guild is an arts organization that explores culture and society through technology and performance.
    Founded in 2015, it seeks to cultivate and support an interest in the creative use of technology in DC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://edgewoodmagiciansguild.com" # the base hostname & protocol for your site
twitter_username: edgewoodmagiciansguild
github_username:  edgewoodmagiciansguild

# Build settings
markdown: kramdown

#Gems
gems:
  - octopress-autoprefixer
